### PR TITLE
Add support for embedding media

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hahaha... this looks so much like this: https://github.com/jbalsas/alloy-editor/commits/AE-233-Embed

I was missing the `paste` part, but had a command and a button instead :wink:

**Comment by jbalsas** [comment]
BTW, I'm with the familiy this weekend, so I won't have time to look into this until tomorrow. I'm more than fine with your version. You can take a look into the command and button part on my branch and bring it to yours, could be useful...

I think it should be fine using CKEditor's service (saw your twitter question), but I'll also start asking on monday regarding our own service... that would give us the option of supporting more complex embed objects in the future...

**Comment by ipeychev** [comment]
Wow, what a coincidence! It is cool we were thinking the same. :)
Okay then, so let's do that - we get as a reference your branch, because it more close to something real, mine is something home brewed for 25 mins. We can keep the button, command, the widget as you did, but let's also allow them to paste links. You may get that from my branch.

This approach also depends on what CKEditor will say about their service, otherwise we shall push Liferay to provide a machine. Once we have it, it should be easy to deploy the service there.

Have fun with you family!

Thanks,

**Comment by jbalsas** [comment]
Hey Iliyan, I'll try to finish this today so we can finally close our `1.0.0` release :wink:

**Comment by ipeychev** [comment]
Great, Chema!

**Pull request closed without merging**
